version: "3"
services:
    client:
        build: client
        restart: always
        ports:
            - "8000:8000"
        volumes: [./client:/client, /client/node_modules]
        links:
            - backend
        stdin_open: true
        networks: [webappnetwork]
    backend:
        build: backend
        restart: always
        ports:
            - "3000:3000"
        volumes: [./backend:/backend, /backend/node_modules]
        networks: [webappnetwork]

networks:
    webappnetwork:
        driver: bridge

