version: "3"
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty: true

  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
